let btn = document.getElementById('nextQ');
let output = document.getElementById('output');
let qCountOutput = document.getElementById('qCount');
let qCount;
qCount = 0;

let couple = 
    [
        'So, Shalika Rahma Kencana. Would you like to be my girlfriend?',
        'What\'s the worst habit you have in bed?',
        'What was the worst date you\'ve ever been on?',
        'When\'s the last time you cried?',
        'What\'s the worst swear word you say often?',
        'Have you ever cheated on a boyfriend or girlfriend?',
        'What\'s something dirty that you think about often?',
        'Have you ever sent a nude photograph to someone?',
        'What\'s the worst lie you\'ve ever told?',
        'What couple would you have a threesome with?',
        'What\'s the biggest age gap you\'ve had with a romantic partner?',
        'Have you ever lied to your romantic partner?',
        'Did you ever fantasize about someone other than your boyfriend/girlfriend?',
        'Have you ever done something sexual with another couple?',
        'Did you ever send dirty photographs to another couple?',
        'Would you ever take lingerie photographs?',
        'Who is the loudest in the bedroom?',
        'Did you ever give/get a lap dance to/from someone?',
        'Would you rather be on top or be on bottom?',
        'What\'s your favorite position during intimacy?',
        'Would you rather be the big spoon or the little spoon?',
        'Have you ever hacked into your partners email account?',
        'Did you ever intentionally read your partners text messages?',
        'Would you let your partner read all of your text messages?',
        'Did you ever flirt with someone random on social media?',
        'Did you ever secretly learn the password to your partners phone?',
        'Would you ever consider doing role play in the bedroom?',
        'What song that reminds you of your partner?',
        'Do relationships require 100% honestly?',
        'What don’t you like about me?',
        'What’s one physical feature that you dislike about me?',
        'What’s the most embarrassing fact I know about you?',
        'Have your partner ever (almost) caught you doing something dirty?',
        'Do your partner, or have they ever disappointed you?',
        'How have your partner changed since you have met them?',
        'What was your first impression on your partner\'s family?',
        'When did you first know you were attracted to your partner?',
        'Do you think you\'ll marry your current girlfriend/boyfriend?',
        'If someone offered you $1 million to break up with your girlfriend/boyfriend, would you do it?',
        'Has your boyfriend or girlfriend ever embarrassed you?',
        'Have you ever thought about cheating on your partner?',
        'Do you like hanging out with your parents?',
        'Would you hit your partner for 100$?',
        'Who has the best smile?',
        'Who has the cutest nose?',
        'How about prettiest eyes?',
        'Who\'s the funniest in this room?',
        'Would you choose a wild, hot relationship or a calm and stable one?',
        'What\'s the most flirtatious thing you\'ve ever done?',
    ];

let adult = 
    [
        'What\'s the most illegal thing you\'ve ever done?',
        'Have you ever kissed someone who is in this room?',
        'When did you lose your virginity?',
        'Did you ever kiss someone of your own gender?',
        'How often do you think about having sex?',
        'Have you ever asked someone to take a dirty picture for you?',
        'What\'s one thing that really turns you on about another gender?',
        'Has anyone ever caught you masturbating?',
        'Would you consider yourself more of a dominant or submissive person?',
        'Where is the worst place you\'ve ever had sex?',
        'Did you ever walk in on your parents having sex?',
        'Which celebrity would you like to sleep with or kiss?',
        'Have you ever shared the bed with another couple?',
        'Did you ever have sex at school?',
        'What\'s one random thing you\'ve done in the bedroom?',
        'How often do you fantasize?',
        'What\'s the last thing you remember doing in the bedroom?',
        'Have you ever ate food while having sex?',
        'Did you ever dance sexually for someone?',
        'Have you ever had someone talk dirty to you?',
        'Did you ever want to film a dirty movie?',
        'If you could have sex with anyone in this room, who would it be?',
        'What movie always turn you on?',
        'What\'s your favorite body part on a guy/girl?',
        'What do you like to be called in the bedroom?',
        'Have you ever had sex with someone that you barely knew?',
        'What\'s the last fantasy that you masturbated to?',
        'What\'s the dirtiest sext you\'ve ever sent?',
        'What sexual position are you best at?',
        'Where is one place you wish you could have sex?',
        'Did you ever have sex on an airplane?',
        'Have you ever been intimate in a car?',
        'Did you ever have an intimate encounter in a movie theater?',
        'Have you ever put your hand down a boyfriend or girlfriends pants in public?',
        'When was the first time you made out with someone?',
        'What was the first time you ever French kissed someone?',
        'If you could change one body part on your boyfriend/girlfriend, what would it be?',
        'When\'s the last time you lied about having an orgasm?',
        'Have you ever pretended to have an orgasm for your partner?',
        'What is your favorite swear word?',
        'Have you ever been attracted to the same sex?',
        'How many sex toys do you own?',
        'Would you rather lose your sex organs forever or gain 100 pounds?',
        'What was the last thing you masturbated to?',
        'Have you ever gotten an STD?',
        'What’s your biggest turn-on?',
        'If you get paid $100, would you wear your sexiest clothes in public?',
        'How many sexual partners have you had?',
        'Have you ever tried to take a sexy picture of yourself?',
        'If you had to flash just one person in this room, who would it be?',
        'If you haven\'t had your first kiss yet, who in this room do you want to have your first kiss with?',
        'What is your wildest fantasy?',
        'And your biggest turn-off?',
        'Have you ever flashed someone?',
        'Have you ever been to a nudist beach? Would you consider going?',
        'Would you ever consider posing for Playboy?',
        'Who has seen you without clothes on?',
        'Have you ever seen a naughty magazine?',
        'Have you ever searched for something dirty on the internet?',
        'Who do you most want to sleep with, out of everyone here?',
        'What\'s your favorite body part on your partner?',
        'How many people have you kissed?',
        'Do you sleep in the nude?',
        'How much money would we have to pay you for you to agree to flash your boobs?',
        'Have you ever been in a "friends with benefits" situation?',
        'If you had to go skinny dipping with someone, who in this room would you choose?',
        'If I paid you $100, would you wear your sexiest clothes to class?',
    ];

let fun = 
    [
        'When did you last fart?',
        'What\'s one thing you wish you could hire someone to do?',
        'Did you ever cut class in high school?',
        'Have you ever went to a concert completely drunk?',
        'What\'s the grossest thing you\'ve ever done?',
        'What habit did you have as a kid that was gross?',
        'Did you ever fail a class or grade in school?',
        'What\'s the most embarrassing thing your mom/dad caught you doing?',
        'Did you ever get diarrhea in public?',
        'If you could be someone else, who would it be?',
        'What\'s the most embarrassing thing that has happened to you?',
        'What kind of underwear do you normally wear?',
        'Can you tie a knot with your tongue?',
        'Have you ever had a secret relationship or online relationship?',
        'What\'s your favorite drink that other people find gross?',
        'What\'s the craziest dream you\'ve ever had?',
        'Have you ever shop lifted?',
        'Did you ever steal anything from a gas station?',
        'Have you ever danced on top of a table?',
        'Did you ever touch someone\'s butt on accident?',
        'Would you make out with me for one minute?',
        'What is the funniest thing your grandparents have ever said?',
        'What is your favorite swear word?',
        'Have you ever been attracted to the same sex?',
        'What was the last thing you searched for on your phone?',
        'If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?',
        'Have you ever played Cards Against Humanity with your parents?',
        'What\'s the first thing you would do if you woke up one day as the opposite sex?',
        'Have you ever walked into a wall?',
        'What would be in your web history that you’d be embarrassed if someone saw?',
        'What color underwear are you wearing right now?',
        'How often do you wash your undergarments?',
        'If you lost one day of your life every time you said a swear word, would you try not to do it?',
        'If you were reborn, what decade would you want to be born in?',
        'If you could suddenly become invisible, what would you do?',
        'Have you ever been caught checking someone out?',
        'Would you rather be caught picking your nose or picking a wedgie?',
        'Have you ever posted something on social media that you regret?',
        'The world ends next week, and you can do anything you want (even if it\'s illegal). What would you do?',
        'What is the most childish thing that you still do?',
        'How far would you go to land the guy or girl of your dreams?',
        'Tell us about a time you embarrassed yourself in front of a crush.',
        'When was the last time you wet the bed?',
        'Have you ever accidentally hit something with your car?',
        'If you had to make out with any Disney character, who would it be?',
        'Have you ever wanted to try LARP (Live Action Role-Play)?',
        'Do you dance when you’re by yourself?',
        'What song on the radio do you sing with every time it comes on?',
        'If you were home by yourself all day, what would you do?',
        'What is something you’ve done to try to be ‘cooler’?',
        'Have you ever got caught doing something you shouldn’t?',
        'Have you ever pooped your pants?',
        'If you could be reincarnated into anyone\'s body, who would you want to become?',
        'What\'s the most useless piece of knowledge you know?',
        'Is it better to use shampoo as soap or soap as shampoo?',
        'Would you rather eat dog food or cat food?',
    ];

let friend = 
    [
        'Would you let someone in this room read text messages on your phone?',
        'Did you ever borrow money from your friend?',
        'Have you ever fantasized about your friends parent or parents?',
        'Did you ever let a friend cheat on one of your tests?',
        'Did you ever cheat in school?',
        'What was your last first date like?',
        'Did you ever try to steal your best friends crush?',
        'What is a nickname your friend used to call you?',
        'Did you ever visit adult websites?',
        'Would you ever steal your friends ex-boyfriend or ex-girlfriend?',
        'Have you ever flirted with a friends boyfriend/girlfriend?',
        'Did you ever decide to listen to a song just because your friend liked it?',
        'If you could change one thing about your friend, what would it be?',
        'If you could eliminate one friend from the group, who would it be?',
        'When did you know that you had a best friend?',
        'Did you ever have a friend get upset at you for something you didn\'t know you did wrong?',
        'Have you ever worn the same underwear multiple days in a row?',
        'What\'s the longest love relationship you\'ve ever been in?',
        'Have you ever had a fantasy about a teacher at school?',
        'Have you ever been a bully or tripped someone on purpose?',
        'How many boyfriends (or girlfriends) have you had?',
        'What don’t you like about me?',
        'Do you actually like my pet dog or cat?',
        'Who has the best dance moves?',
        'Are you still a virgin?',
        'What’s the most embarrassing fact your friend know about you?',
        'Who do you think is the worst-dressed person in this room?',
        'True or false: You have a crush on [fill in the blank]',
        'Of the people in this room, who do you want to trade lives with?',
        'Have you ever peed yourself?',
        'What was your most embarrassing moment in public?',
        'Have you ever farted loudly in class?',
        'Who is your secret crush?',
        'Do you think [fill in the name] is cute?',
        'Who do you like the least in this room, and why?',
        'Who is the sexiest person in this room?',
        'Would you rather have sex with [insert name] in secret or not have sex with that person, but everyone thinks you did?',
        'What don\'t you like about your friend next to you?',
        'If you were rescuing people from a burning building and you had to leave one person behind from this room, who would it be?',
        'Do you think you\'ll marry your current girlfriend/boyfriend?',
        'If you were allowed to marry more than one person, would you? Who would you choose to marry?',
        'Who in this room would be the worst person to date? Why?',
        'Who is one person you pretend to like, but actually don’t?',
        'Do you have any silly nicknames?',
        'Who would you hate to see naked?',
        'How long have you gone without a shower?',
        'If you could only text one person for the rest of your life, but you could never talk to that person face-to-face, who would that be?',
        'How long have you gone without brushing your teeth?',
        'If your car broke down in the middle of the road, who in this room would be the last person you would call? Why?',
        'What\'s the best thing to say to your friend that would be the worst thing to say to your crush?',
        'What if your best friend told you that she liked your crush?',
        'If you knew your friend\'s boyfriend was cheating on her, what would you do?',
        'Have you ever told a lie about your best friend to make yourself look better?',
        'If you had to date someone else\'s partner, who would it be?',
        'Have you ever shared your friend\'s secret with someone else?',
        'Rate everyone in the room from 1 to 10, with 10 being the hottest.',
        'Would you share a toothbrush with your best friend?',
        'Have you ever ignored a friend\'s text? Why did you do it?',
        'Have you ever lied to your best friend?',
        'If your friend asked you to lie for her and you knew you would get in trouble, would you do it?',
        'Of the people in this room, who would you go out with?',
        'Describe the most attractive thing about each person in this room.',
        'Who here do you think would be the best kisser?',
        'If you could have one physical feature of someone in this room, what would that be?',
        'If you had one week to live and you had to marry someone in this room, who would it be?',
        'If you only had 24 hours to live and you could do anything with anyone in this room, who would it be and what would you do with that person?',
    ];

let basic = 
    [
        'What\'s the worst food you\'ve ever ate?',
        'What\'s a pet name that your mom/dad always calls you?',
        'Have you ever got into a fist fight with another person?',
        'What\'s the last lie you told your best friend?',
        'What\'s one secret that you promised you\'d never tell?',
        'Have you ever worn the same underwear multiple days in a row?',
        'Have you ever bought something, worn it, and then returned it?',
        'Did you ever break something in the house as a kid?',
        'What rule did you always break when you were a child?',
        'Have you ever broken the law?',
        'What\'s the one thing you really dislike about yourself',
        'If you had to pick one thing you love about yourself, what would it be?',
        'What\'s your favorite part of your family traditions?',
        'Did you ever turn a t-shirt inside out to wear it again?',
        'Did you ever watch a movie that was rated higher than your age?',
        'Have you ever had a sip of alcohol?',
        'Did you ever lie to someone at church?',
        'Did you ever have an embarrassing thing happen to you and then lie about it?',
        'Would you go out with an older woman/man?',
        'Have you ever fallen in love at first sight?',
        'When was the last time you flexed in the mirror?',
        'When was the last time you cried?',
        'Do you actually like your friend\'s pet dog or cat?',
        'Have you ever been fired from your job?',
        'After you\'ve dropped a piece of food, what\'s the longest time you\'ve left it on the ground and then ate it?',
        'Have you ever tasted a booger?',
        'Have you ever peed in the pool?',
        'Have you ever farted in an elevator?',
        'What are some things you think about when sitting on the toilet?',
        'Did you have an imaginary friend growing up?',
        'Do you cover your eyes during a scary part in a movie?',
        'Have you ever practiced kissing in a mirror?',
        'Did your parents ever give you the “birds and the bees” talk?',
        'What is your guilty pleasure?',
        'What is your worst habit?',
        'Has anyone ever walked in on you when going #2 in the bathroom?',
        'Have you ever had a wardrobe malfunction?',
        'Do you sing in the shower?',
        'Do you ever talk to yourself in the mirror?',
        'Do you sleep with a stuffed animal?',
        'Do you drool in your sleep?',
        'Do you talk in your sleep?',
        'What is your go-to song for the shower?',
        'How would you rate your looks on a scale of 1 to 10?',
        'What was the last thing you texted?',
        'Have you ever tasted ear wax?',
        'Have you ever farted and then blamed someone else?',
        'Have you ever tasted your sweat?',
        'Who is your favorite: Mom or Dad?',
        'Would you trade your sibling in for a million dollars?',
        'Would you trade in your dog for a million dollars?',
        'Would you choose to save 100 people without anyone knowing about it or not save them but have everyone praise you for it?',
        'If you could only hear one song for the rest of your life, what would it be?',
        'Would you rather live with no internet or no A/C or heating?',
        'If you could go back in time in erase one thing you said or did, what would it be?',
        'What\'s the longest time you\'ve stayed in the bathroom, and why did you stay for that long?',
        'Have you ever cried because you missed your parents so much?',
        'Describe the strangest dream you\'ve ever had. Did you like it?',
        'What is your biggest fear?',
        'Do you pee in the shower?',
        'Have you ever kept a library book?',
        'What children’s movie could you watch over and over again?',
        'Do you have bad foot odor?',
        'What app on your phone do you waste the most time on?',
        'Have you ever pretended to be sick to get out of something? If so, what was it?',
        'Are you scared of the dark?',
        'How many selfies do you take a day?',
        'When was the last time you brushed your teeth?',
        'Have you ever butt-dialed someone?',
        'What was the last R-rated movie you watched?',
        'What is something that no one else knows about you?',
        'Do you write in a diary?',
        'What\'s one food that you will never order at a restaurant?',
        'Would you rather not shower for a month, or eat the same meal every day for a month?',
    ];

function* shuffle(array) {

    var i = array.length;

    while (i--) {
        yield array.splice(Math.floor(Math.random() * (i+1)), 1)[0];
    }

}
var ranNums = shuffle([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,
    29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48]);

btn.addEventListener('click', function(){
    // var randomQuote = couple[Math.floor(Math.random() * couple.length)]
    // output.innerHTML = randomQuote
    qCount++

    if (qCount == 5) {
        btn.innerHTML = "YES"
        output.innerHTML = couple[0];
        qCountOutput.innerHTML = "Question Number " + qCount;
    } 
    // else if (condition2) {

    // } 
    else {
        output.innerHTML = couple[ranNums.next().value];
        btn.innerHTML = "Next Question"
        qCountOutput.innerHTML = "Question Number " + qCount;
    }

    
})